cargo-features = ["edition2024"]

[package]
name = "week31"
version = "0.1.0"
edition = "2024"

[lib]                                   #
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "1.6.0"
borsh-derive = "1.6.0"
solana-program = "3.0.0"
